version: '3'
services:
  openstack-monitoring:
    restart: always
    image: ghcr.io/pixelvirt/openstack-go:latest
    env_file:
      - .env
    ports:
      - "9092:9092"    
    container_name: openstack-monitoring

